function unityData = importUnityData(filename,comdecsep)
if nargin<2
    comdecsep = 0;
end
%IMPORTFILE Import data from a text file
%  INFOTABLE = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  INFOTABLE = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  InfoTable = importfile("C:\DATA\OPM_Tremor_project\OPM_SF_290921\StimuliPCLocal\SF\SF_Rep_2\InfoTable.txt", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 19-Oct-2021 17:07:56

%% Input handling


% % If dataLines is not specified, define defaults
% if nargin < 2
    dataLines = [1, Inf];
% end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 9);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = [" ", ","];

% Specify column names and types
opts.VariableNames = ["Condition", "Repetition", "Direction", "Balloon_Appeared", "Balloon_Popped", "Time_of_Popping", "Execution_Delay", "Hold_Time", "Correct_Balloon_Time"];
opts.VariableTypes = ["double", "double", "double", "categorical", "categorical", "double", "double", "double", "categorical"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";

% Specify variable properties
opts = setvaropts(opts, ["Balloon_Appeared", "Balloon_Popped", "Correct_Balloon_Time"], "EmptyFieldRule", "auto");
if comdecsep
opts = setvaropts(opts, "Execution_Delay", "DecimalSeparator", ",");   
end
% Import the data
unityData = readtable(filename, opts);
unityData = unityData(2:end,:);
end