function AVData = importEngAVData_CODER(filename,fsamp)
% Script for importing data from the following text file:
%
% Auto-generated by MATLAB on 05-Oct-2021 09:37:59

opts = delimitedTextImportOptions("NumVariables", 8);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Condition", "Coder", "Timer"];
opts.VariableTypes = ["double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
AVData = readtable(filename, opts);

time_AV = AVData.Timer;
data_AV = [AVData.Coder];

% Remove incomplete rows
data_AV(isnan(time_AV),:) = [];
time_AV(isnan(time_AV),:) = [];

time_AV(any(isnan(data_AV),2),:) = [];
data_AV(any(isnan(data_AV),2),:) = [];

% Resample to Target
tartime_AV = time_AV(1):1./fsamp:time_AV(end);
% Ensure no duplicate points
[C,IA] = unique(time_AV);
time_AV = time_AV(IA);
data_AV = data_AV(IA,:);

trials = interp1(time_AV,data_AV,tartime_AV');
time_AV = tartime_AV;

%% Setup FT data structure
AVData = [];
AVData.fsample = fsamp;
AVData.trial{1} = trials';
AVData.time{1} = time_AV;
AVData.label = {'Coder'};
AVData.chantype = {'Trigger'};

save([fileparts(filename) '\AVData.mat'],'AVData')
end